# Generated by Django 4.1.1 on 2022-10-07 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_percentage',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
