# Generated by Django 4.1.1 on 2022-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_completion_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archieved',
            field=models.BooleanField(default=False),
        ),
    ]
