# Generated by Django 3.2.3 on 2022-10-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_archieved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'backlog'), ('in progress', 'in progress'), ('completed', 'completed')], default='backlog', max_length=255),
        ),
    ]
