# Generated by Django 3.2.3 on 2022-10-12 09:39

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_userprofile_avatar'),
        ('tasks', '0006_log_log_color_log_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_color',
            field=colorfield.fields.ColorField(default='#955251', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[('Task Created', 'Task Created'), ('Task Updated', 'Task Updated')], default='Task Created', max_length=255),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_profiles.userprofile')),
            ],
        ),
    ]
