# Generated by Django 3.2.3 on 2022-10-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_userprofile_position'),
        ('tasks', '0007_auto_20221012_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user_profiles.userprofile'),
        ),
    ]
